name: Scala CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up JDK 11
#        uses: actions/setup-java@v4
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: 'sbt'
#      - name: Run tests
#        run: sbt test

jobs:
  build-scala-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: coursier/setup-action@v1
        with:
          jvm: corretto:11.0.26.4.1
          apps: sbt

      - name: Run tests
        run:  |
          echo "Checking ubuntu, java, and sbt ... "
          cat /etc/issue
          java -version
          sbt --version
          echo "Environment variables..."
          printenv
          echo "Building and running unit tests..."
          sbt test

      - name: Run Main
        run: |
          echo "Running Main..."
          sbt run

      - name: Build Fat Jar
        run: |
          sbt clean assembly
          ls -lah target/scala-2.13

